export {
  addAdmissionLocation,
  addDepartment,
  addOutpatientDepartment,
  deleteAdmissionLocation,
  deleteDepartment,
  deleteOutpatientDepartment,
  deleteUserProfile,
  fallbackAdmissionLocations,
  fallbackDepartments,
  fallbackOutpatientDepartments,
  subscribeToAdmissionLocations,
  subscribeToDepartments,
  subscribeToOutpatientDepartments,
  subscribeToUsers,
  updateAdmissionLocation,
  updateDepartment,
  updateOutpatientDepartment,
  updateUserAccess,
} from "./recordsService";
